"""create work items table

Revision ID: 0e253fc75960
Revises: 9729724884aa
Create Date: 2026-08-17 19:30:54.801594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e253fc75960'
down_revision: Union[str, Sequence[str], None] = '9729724884aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('current_stage_definition_id', sa.Uuid(), nullable=False),
    sa.Column('risk_status', sa.String(length=50), server_default='on_track', nullable=False),
    sa.Column('accountable_owner_id', sa.Uuid(), nullable=False),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_target_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['accountable_owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_stage_definition_id'], ['stage_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_accountable_owner_id'), 'work_items', ['accountable_owner_id'], unique=False)
    op.create_index(op.f('ix_work_items_current_stage_definition_id'), 'work_items', ['current_stage_definition_id'], unique=False)
    op.create_index(op.f('ix_work_items_organization_id'), 'work_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_items_template_version_id'), 'work_items', ['template_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_items_template_version_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_organization_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_current_stage_definition_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_accountable_owner_id'), table_name='work_items')
    op.drop_table('work_items')
    # ### end Alembic commands ###
