"""create stage and field definitions tables

Revision ID: 9729724884aa
Revises: 6a0886d08925
Create Date: 2026-08-09 00:13:34.184285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9729724884aa'
down_revision: Union[str, Sequence[str], None] = '6a0886d08925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=200), nullable=True),
    sa.Column('validation_config', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'key', name='uq_field_definitions_version_key')
    )
    op.create_index(op.f('ix_field_definitions_template_version_id'), 'field_definitions', ['template_version_id'], unique=False)
    op.create_table('stage_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_owner_role_id', sa.Uuid(), nullable=True),
    sa.Column('sla_minutes', sa.Integer(), nullable=True),
    sa.Column('terminal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['default_owner_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'code', name='uq_stage_definitions_version_code')
    )
    op.create_index(op.f('ix_stage_definitions_template_version_id'), 'stage_definitions', ['template_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_definitions_template_version_id'), table_name='stage_definitions')
    op.drop_table('stage_definitions')
    op.drop_index(op.f('ix_field_definitions_template_version_id'), table_name='field_definitions')
    op.drop_table('field_definitions')
    # ### end Alembic commands ###
