"""create work item values and stage history tables

Revision ID: a8491af97e4a
Revises: 0e253fc75960
Create Date: 2026-08-18 00:55:37.854931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8491af97e4a'
down_revision: Union[str, Sequence[str], None] = '0e253fc75960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=False),
    sa.Column('stage_definition_id', sa.Uuid(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_source', sa.String(length=50), nullable=False),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_definition_id'], ['stage_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_history_stage_definition_id'), 'stage_history', ['stage_definition_id'], unique=False)
    op.create_index(op.f('ix_stage_history_work_item_id'), 'stage_history', ['work_item_id'], unique=False)
    op.create_index('uq_stage_history_open_work_item', 'stage_history', ['work_item_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_table('work_item_field_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=False),
    sa.Column('field_definition_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=200), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('set_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'field_definition_id', name='uq_work_item_field_values_work_item_definition')
    )
    op.create_index(op.f('ix_work_item_field_values_field_definition_id'), 'work_item_field_values', ['field_definition_id'], unique=False)
    op.create_index(op.f('ix_work_item_field_values_work_item_id'), 'work_item_field_values', ['work_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_item_field_values_work_item_id'), table_name='work_item_field_values')
    op.drop_index(op.f('ix_work_item_field_values_field_definition_id'), table_name='work_item_field_values')
    op.drop_table('work_item_field_values')
    op.drop_index('uq_stage_history_open_work_item', table_name='stage_history', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_index(op.f('ix_stage_history_work_item_id'), table_name='stage_history')
    op.drop_index(op.f('ix_stage_history_stage_definition_id'), table_name='stage_history')
    op.drop_table('stage_history')
    # ### end Alembic commands ###
